services:
  db:
    image: postgres:15
    container_name: troutfarm-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: troutfarm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    image: troutfarm-backend:latest
    container_name: troutfarm-app
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/troutfarm
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_PROFILES_ACTIVE: docker

volumes:
  pgdata: